defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"
source: ['_includes']
include: ['_pages']
relative_permalinks: false
baseurl: "/PiWeb-Customplot"
gems:
  - jekyll-redirect-from